### PR TITLE
Revert "Hack for JP iTunes and Unicode Metadata Support"

### PR DESCRIPTION
**Pull request by nint8835**
Reverts nint8835/iTunesRichPresence#3. Hack appeared to initially work, but can cause garbled text. For example, [https://i.bootleg.technology/Tzu9IGyHeh.png](https://i.bootleg.technology/Tzu9IGyHeh.png)

### CODE REVIEW

**Comment by nint8835** [comment]
@FukujiMihoko

**Comment by FukujiMihoko** [comment]
Hey @nint8835!

Can you please send me the audio file that caused this (or just the metadata)? I'd love to debug it!

**Comment by nint8835** [comment]
Do you have some way that I can DM it to you, or something?

**Comment by FukujiMihoko** [comment]
I'm Maav#0408 on Discord.

**Pull request merged**
